---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    - name: Configurando /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 10.11.12.103 registry registry.gpxlnx.me

    - name: Copiando get-docker.sh
      ansible.builtin.copy:
        src: files/get-docker.sh
        dest: /root/get-docker.sh

    - name: Executa script
      command: sh /root/get-docker.sh

    - name: Start Docker, if not started
      ansible.builtin.service:
        name: docker
        state: started
